name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint --ext .js,.jsx src test
      - name: Run unit tests
        run: npm run test:unit
      - name: Build
        run: |
          npm run build
          cp -r assets dist/
          cp dist/index.html dist/404.html
          cp favicon.ico dist/
      - name: Run E2E tests
        run: npm run test:ci-e2e
        env:
          HEADLESS: true
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: dist
